# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Martinovy Recepty
google_analytics_tracking_id:

menu:
  -
    name: "Bublina"
    url: "bublanina"
  -
    name: "Ovocné knedlíky"
    url: "ovocne-knedliky"
  -
    name: "Tvarohový nákyp"
    url: "tvarohovy-nakyp"
  -
    name: "Rychlý koláč s ovocem"
    url: "rychly-kolac-s-ovocem"
  -
    name: "Utopence od dědy"
    url: "utopence-od-dedy"
  -
    name: "Čočkovka"
    url: "cockovka"
  -
    name: "Cuketový nákyp"
    url: "cuketovy-nakyp"
  -
    name: "Šunkafleky"
    url: "sunkafleky"
  -
    name: "Knedlíky plněné uzeným se zelím"
    url: "knedliky-plnene-uzenym"
