title: Martinovy Recepty

categories:
    -
        name: Polévky
        slug: soup
    -
        name: Hlavní jídla
        slug: main
    -
        name: Hlavní jídla - sladká
        slug: main-sweet
    -
        name: Pomazánky
        slug: spread
    -
        name: Dezerty
        slug: dessert
    -
        name: Ostatní
        slug: misc
    -
        name: Vánoční cukroví
        slug: christmas-cookies
